[package]
authors = ["jD91mZM2 <me@krake.one>"]
description = "A Nix parser written in Rust"
edition = "2018"
license = "MIT"
name = "rnix"
readme = "README.md"
repository = "https://github.com/nix-community/rnix-parser"
version = "0.7.3"

[[bench]]
harness = false
name = "all-packages"

[dependencies]
rowan = "0.9.0"
cbitset = "0.2.0"

[dev-dependencies]
criterion = "0.3.0"
