[package]
authors = ["jD91mZM2 <me@krake.one>"]
description = "A Nix parser written in Rust"
edition = "2018"
license = "MIT"
name = "rnix"
readme = "README.md"
repository = "https://gitlab.com/jD91mZM2/rnix"
version = "0.6.0"

[[bench]]
harness = false
name = "all-packages"

[dependencies]
rowan = "0.5.1"
cbitset = "0.2.0"

[dev-dependencies]
criterion = "0.2.11"
